# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install hatch
    - name: Build and publish
      run: |
        hatch build

    - name: Auditwheel repair (Linux only)
      if: runner.os == 'Linux'
      run: |
        python -m pip install auditwheel
        for whl in dist/*.whl; do
          auditwheel repair "$whl" -w dist/
          rm "$whl"
        done

    - name: Publish to PyPI
      run: |
        hatch publish -u __token__ -a ${{ secrets.PYPI_API_TOKEN }}
